#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      mkdir -p /data/nginx/{log,run,html}
      exec nginx -c $shome/etc/nginx/nginx.conf -g 'daemon off;'
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

main "$@"
